/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactFormData = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'createForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'delete' : IDL.Func([IDL.Nat], [], []),
  'getAllForms' : IDL.Func([], [IDL.Vec(ContactFormData)], ['query']),
  'getAllFormsByEmail' : IDL.Func([], [IDL.Vec(ContactFormData)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactFormData = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'createForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'delete' : IDL.Func([IDL.Nat], [], []),
    'getAllForms' : IDL.Func([], [IDL.Vec(ContactFormData)], ['query']),
    'getAllFormsByEmail' : IDL.Func([], [IDL.Vec(ContactFormData)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };